- name: yum-clean-all
  command: yum clean all
  args:
    warn: no

- name: Install NTP service
  yum:
    name: ntp
    state: installed
  ignore_errors: true

- name: Install Unzip service
  yum:
    name: unzip
    state: installed
  ignore_errors: true

- name: Make sure the NTP service is enabled
  service:
    name: ntpd
    enabled: yes
  ignore_errors: true

- name: Set swappiness to 0
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
    reload: yes
    ignoreerrors: yes

- name: Stop the iptables service
  service:
    name: iptables
    state: stopped
  ignore_errors: true

- name: Disable the iptables firewall service
  service:
    name: iptables
    enabled: no
  ignore_errors: true

- name: Stop the firewalld service
  service:
    name: firewalld
    state: stopped
  ignore_errors: true

- name: Disable the firewalld firewall service
  service:
    name: firewalld
    enabled: no
  ignore_errors: true

- name: Disable Transparent Huge Pages until the next reboot
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
  args:
    removes: /sys/kernel/mm/transparent_hugepage/enabled


- name: Install epel
  yum:
    name: epel-release
    state: installed
  ignore_errors: true

- name: Disable selinux
  selinux:
    state: disabled

- name: Check is umask Value exists
  command: grep "umask 0022" /etc/profile
  register: umask
  always_run: True
  ignore_errors: True
  changed_when: False

- name: Updating umask Value
  shell: echo umask 0022 >> /etc/profile
  when: umask.rc != 0

- name: Install OpenJDK-1.8
  yum:
    name: java-1.8.0-openjdk
    state: installed

- name: Install OpenJDK-1.8 Devel Packages
  yum:
    name: java-1.8.0-openjdk-devel
    state: installed

- name: Downloading Hadoop 3.0 Distribution
  get_url: url='http://apachemirror.wuchna.com/hadoop/common/stable/hadoop-3.2.1.tar.gz' dest='/tmp/hadoop-3.2.1.tar.gz' mode=0644

- name: Unarchive Hadoop
  unarchive:
    src: /tmp/hadoop-3.2.1.tar.gz
    dest: /etc/
    remote_src: yes

- name: Set to the root of your Java installation
  blockinfile:
    path: /etc/hadoop/hadoop-env.sh
    block: |
      export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64
