######## Pre-requistes ##########

- name: Install Python
  yum:
    name: ntp
    state: installed
  ignore_errors: true

- name: Install Python Virtual Enviornment Package
  shell: pip install virtualenv

######## Setup Hadoop Service Handler ##############

- name: Copy Service Handler Scripts
  copy: src={{item}} dest=/etc/init.d/{{item}}
  with_items:
    - hadoop
    - hdfs
    - yarn

- name: Enable Service Handler Script
  shell: |
    chmod +x /etc/init.d/{{item}}
    chkconfig --add {{item}}
  with_items:
    - hadoop
    - hdfs
    - yarn

- name: Start Hadoop
  shell: service hadoop start
