
- name: Install Python and Pip
  yum:
    name: {{item}}
    state: installed
  with_items:
   - python3
   - python3-pip
   - zip

- name: Install Python Virtual Enviornment Package
  shell: pip3 install virtualenv

- name: Copy Python Package Requirement
  copy: src=requirement.txt dest=/tmp/requirement.txt

- name: Setting up Virtual Env and Installing Packages
  shell: |
    mkdir /tmp/asg2_virtualenv
    cd /tmp/asg2_virtualenv
    python3 -m venv venv
    source venv/bin/activate
    for i in `cat /tmp/requirement.txt`; do pip install $i; done
    zip -r /tmp/venv.zip /tmp/asg2_virtualenv/venv/
