#!/bin/bash
# chkconfig: 2345 20 80
# description: Manage Hadoop Services

# Source function library.
. /etc/init.d/functions

start() {
        /usr/hadoop-3.2.1/sbin/start-all.sh
}

stop() {
        /usr/hadoop-3.2.1/sbin/stop-all.sh
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    *)
       echo "Usage: $0 {start|stop|restart}"
esac

exit 0
